<?php
if($model->caracteristicasConstruccion!=null){
 $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['NPisos'],
			'value'=>$model->caracteristicasConstruccion->NPisos,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['NSotanos'],
			'value'=>$model->caracteristicasConstruccion->NSotanos,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['existeMezanine'],
			'value'=>$model->caracteristicasConstruccion->existeMezanine,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['pisoRiesgo'],
			'value'=>$model->caracteristicasConstruccion->pisoRiesgo,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['areaRiesgo'],
			'value'=>$model->caracteristicasConstruccion->areaRiesgo,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['mamposteriaReforzada'],
			'value'=>$model->caracteristicasConstruccion->mamposteriaReforzada,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['mamposteriaConfinada'],
			'value'=>$model->caracteristicasConstruccion->mamposteriaConfinada,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['sistemaReticularCelulado'],
			'value'=>$model->caracteristicasConstruccion->sistemaReticularCelulado,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['SistemaPorticoConcreto'],
			'value'=>$model->caracteristicasConstruccion->SistemaPorticoConcreto,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['unaDireccionC'],
			'value'=>$model->caracteristicasConstruccion->unaDireccionC,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['dosDireccionesC'],
			'value'=>$model->caracteristicasConstruccion->dosDireccionesC,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['sistemaPorticoAcero'],
			'value'=>$model->caracteristicasConstruccion->sistemaPorticoAcero,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['unaDireccionA'],
			'value'=>$model->caracteristicasConstruccion->unaDireccionA,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['dosDireccionesA'],
			'value'=>$model->caracteristicasConstruccion->dosDireccionesA,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['sistemaDualConcreto'],
			'value'=>$model->caracteristicasConstruccion->sistemaDualConcreto,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['sistemaMurosEstructurales'],
			'value'=>$model->caracteristicasConstruccion->sistemaMurosEstructurales,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['maderaTejaBarro'],
			'value'=>$model->caracteristicasConstruccion->maderaTejaBarro,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['cerchaMetalicaTejaLiviana'],
			'value'=>$model->caracteristicasConstruccion->cerchaMetalicaTejaLiviana,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['losaConcreto'],
			'value'=>$model->caracteristicasConstruccion->losaConcreto,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['otro'],
			'value'=>$model->caracteristicasConstruccion->otro,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['cual'],
			'value'=>$model->caracteristicasConstruccion->cual,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['deterioro'],
			'value'=>$model->caracteristicasConstruccion->deterioro,
		),
		array(
			'label'=>$model->caracteristicasConstruccion->attributeLabels()['observaciones'],
			'value'=>$model->caracteristicasConstruccion->observaciones,
		),
	),
)); 
}else{
	echo "No se ha ingresado Caracteristicas de la Construcción";
}
?>