<?php
if($model->caracteristicasInstalacion!=null){
 $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['acueductoPropio'],
			'value'=>$model->caracteristicasInstalacion->acueductoPropio,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aRedPublica'],
			'value'=>$model->caracteristicasInstalacion->aRedPublica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aCual'],
			'value'=>$model->caracteristicasInstalacion->aCual,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['estadoRejillas'],
			'value'=>$model->caracteristicasInstalacion->estadoRejillas,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['estadoCanales'],
			'value'=>$model->caracteristicasInstalacion->estadoCanales,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['estadoAlcantarillas'],
			'value'=>$model->caracteristicasInstalacion->estadoAlcantarillas,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['limpiezaTechos'],
			'value'=>$model->caracteristicasInstalacion->limpiezaTechos,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['estadoBajantes'],
			'value'=>$model->caracteristicasInstalacion->estadoBajantes,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['plantaElectrica'],
			'value'=>$model->caracteristicasInstalacion->plantaElectrica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pEMarca'],
			'value'=>$model->caracteristicasInstalacion->pEMarca,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pEAño'],
			'value'=>$model->caracteristicasInstalacion->pEAño,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pEPotencia'],
			'value'=>$model->caracteristicasInstalacion->pEPotencia,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pECombustible'],
			'value'=>$model->caracteristicasInstalacion->pECombustible,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pEUbicacionFisica'],
			'value'=>$model->caracteristicasInstalacion->pEUbicacionFisica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['pEZonaAlimenta'],
			'value'=>$model->caracteristicasInstalacion->pEZonaAlimenta,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['transformadorPropio'],
			'value'=>$model->caracteristicasInstalacion->transformadorPropio,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['tPMarca'],
			'value'=>$model->caracteristicasInstalacion->tPMarca,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['tPAño'],
			'value'=>$model->caracteristicasInstalacion->tPAño,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['tPCapacidad'],
			'value'=>$model->caracteristicasInstalacion->tPCapacidad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['tPUbicacionFisica'],
			'value'=>$model->caracteristicasInstalacion->tPUbicacionFisica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sistemaGas'],
			'value'=>$model->caracteristicasInstalacion->sistemaGas,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sGRedPublica'],
			'value'=>$model->caracteristicasInstalacion->sGRedPublica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sGTanqueAlmacenamiento'],
			'value'=>$model->caracteristicasInstalacion->sGTanqueAlmacenamiento,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sGCapacidadTanque'],
			'value'=>$model->caracteristicasInstalacion->sGCapacidadTanque,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sGUtilizaCilindros'],
			'value'=>$model->caracteristicasInstalacion->sGUtilizaCilindros,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sGCapacidad'],
			'value'=>$model->caracteristicasInstalacion->sGCapacidad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['sistemaAireAcondicionado'],
			'value'=>$model->caracteristicasInstalacion->sistemaAireAcondicionado,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aATipoSistema'],
			'value'=>$model->caracteristicasInstalacion->aATipoSistema,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aACapacidad'],
			'value'=>$model->caracteristicasInstalacion->aACapacidad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aATorreEnfriamiento'],
			'value'=>$model->caracteristicasInstalacion->aATorreEnfriamiento,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aATECapacidad'],
			'value'=>$model->caracteristicasInstalacion->aATECapacidad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['aATECantidad'],
			'value'=>$model->caracteristicasInstalacion->aATECantidad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoInstalacionesFisicas'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoInstalacionesFisicas,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mIFPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mIFPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoPlantaElectrica'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoPlantaElectrica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mPEPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mPEPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientosubestaciónElectrica'],
			'value'=>$model->caracteristicasInstalacion->mantenimientosubestaciónElectrica,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mSEPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mSEPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoTransformadorPropio'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoTransformadorPropio,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mTPPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mTPPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoSistemaGas'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoSistemaGas,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mSGPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mSGPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoAscensores'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoAscensores,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mAPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mAPersonalACargo,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mantenimientoDispositivosSeguridad'],
			'value'=>$model->caracteristicasInstalacion->mantenimientoDispositivosSeguridad,
		),
		array(
			'label'=>$model->caracteristicasInstalacion->attributeLabels()['mDSPersonalACargo'],
			'value'=>$model->caracteristicasInstalacion->mDSPersonalACargo,
		),
	),
)); 
}else{
	echo "No se ha ingresado Caracteristicas de las Instalaciones";
}
?>